/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppPeopleRouteImport } from './routes/_app/people'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as AppHistoryIndexRouteImport } from './routes/_app/history.index'
import { Route as AppHistoryDateRouteImport } from './routes/_app/history.$date'
import { Route as AppHistoryCatchUpRouteImport } from './routes/_app/history.catch-up'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people.index'
import { Route as AppPeopleMemberIdRouteImport } from './routes/_app/people.$memberId'
import { Route as AppWardrobeIndexRouteImport } from './routes/_app/wardrobe.index'
import { Route as AppWardrobeGarmentIdRouteImport } from './routes/_app/wardrobe.$garmentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiGarmentsUploadRouteImport } from './routes/api/garments/upload'
import { Route as ApiInternalTickRouteImport } from './routes/api/internal/tick'
import { Route as ApiMediaSplatRouteImport } from './routes/api/media/$'
import { Route as ApiGarmentsGarmentIdPhotoRouteImport } from './routes/api/garments/$garmentId.photo'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryIndexRoute = AppHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryDateRoute = AppHistoryDateRouteImport.update({
  id: '/history/$date',
  path: '/history/$date',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryCatchUpRoute = AppHistoryCatchUpRouteImport.update({
  id: '/history/catch-up',
  path: '/history/catch-up',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPeopleRoute,
} as any)
const AppPeopleMemberIdRoute = AppPeopleMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => AppPeopleRoute,
} as any)
const AppWardrobeIndexRoute = AppWardrobeIndexRouteImport.update({
  id: '/wardrobe/',
  path: '/wardrobe/',
  getParentRoute: () => AppRoute,
} as any)
const AppWardrobeGarmentIdRoute = AppWardrobeGarmentIdRouteImport.update({
  id: '/wardrobe/$garmentId',
  path: '/wardrobe/$garmentId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGarmentsUploadRoute = ApiGarmentsUploadRouteImport.update({
  id: '/api/garments/upload',
  path: '/api/garments/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalTickRoute = ApiInternalTickRouteImport.update({
  id: '/api/internal/tick',
  path: '/api/internal/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaSplatRoute = ApiMediaSplatRouteImport.update({
  id: '/api/media/$',
  path: '/api/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGarmentsGarmentIdPhotoRoute =
  ApiGarmentsGarmentIdPhotoRouteImport.update({
    id: '/api/garments/$garmentId/photo',
    path: '/api/garments/$garmentId/photo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/people': typeof AppPeopleRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/history/$date': typeof AppHistoryDateRoute
  '/history/catch-up': typeof AppHistoryCatchUpRoute
  '/people/$memberId': typeof AppPeopleMemberIdRoute
  '/wardrobe/$garmentId': typeof AppWardrobeGarmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/garments/upload': typeof ApiGarmentsUploadRoute
  '/api/internal/tick': typeof ApiInternalTickRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/history/': typeof AppHistoryIndexRoute
  '/people/': typeof AppPeopleIndexRoute
  '/wardrobe/': typeof AppWardrobeIndexRoute
  '/api/garments/$garmentId/photo': typeof ApiGarmentsGarmentIdPhotoRoute
}
export interface FileRoutesByTo {
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/settings': typeof AppSettingsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/': typeof AppIndexRoute
  '/history/$date': typeof AppHistoryDateRoute
  '/history/catch-up': typeof AppHistoryCatchUpRoute
  '/people/$memberId': typeof AppPeopleMemberIdRoute
  '/wardrobe/$garmentId': typeof AppWardrobeGarmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/garments/upload': typeof ApiGarmentsUploadRoute
  '/api/internal/tick': typeof ApiInternalTickRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/history': typeof AppHistoryIndexRoute
  '/people': typeof AppPeopleIndexRoute
  '/wardrobe': typeof AppWardrobeIndexRoute
  '/api/garments/$garmentId/photo': typeof ApiGarmentsGarmentIdPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/people': typeof AppPeopleRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/_app/': typeof AppIndexRoute
  '/_app/history/$date': typeof AppHistoryDateRoute
  '/_app/history/catch-up': typeof AppHistoryCatchUpRoute
  '/_app/people/$memberId': typeof AppPeopleMemberIdRoute
  '/_app/wardrobe/$garmentId': typeof AppWardrobeGarmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/garments/upload': typeof ApiGarmentsUploadRoute
  '/api/internal/tick': typeof ApiInternalTickRoute
  '/api/media/$': typeof ApiMediaSplatRoute
  '/_app/history/': typeof AppHistoryIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/wardrobe/': typeof AppWardrobeIndexRoute
  '/api/garments/$garmentId/photo': typeof ApiGarmentsGarmentIdPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/login'
    | '/account'
    | '/people'
    | '/settings'
    | '/api/healthz'
    | '/history/$date'
    | '/history/catch-up'
    | '/people/$memberId'
    | '/wardrobe/$garmentId'
    | '/api/auth/$'
    | '/api/garments/upload'
    | '/api/internal/tick'
    | '/api/media/$'
    | '/history/'
    | '/people/'
    | '/wardrobe/'
    | '/api/garments/$garmentId/photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join'
    | '/login'
    | '/account'
    | '/settings'
    | '/api/healthz'
    | '/'
    | '/history/$date'
    | '/history/catch-up'
    | '/people/$memberId'
    | '/wardrobe/$garmentId'
    | '/api/auth/$'
    | '/api/garments/upload'
    | '/api/internal/tick'
    | '/api/media/$'
    | '/history'
    | '/people'
    | '/wardrobe'
    | '/api/garments/$garmentId/photo'
  id:
    | '__root__'
    | '/_app'
    | '/join'
    | '/login'
    | '/_app/account'
    | '/_app/people'
    | '/_app/settings'
    | '/api/healthz'
    | '/_app/'
    | '/_app/history/$date'
    | '/_app/history/catch-up'
    | '/_app/people/$memberId'
    | '/_app/wardrobe/$garmentId'
    | '/api/auth/$'
    | '/api/garments/upload'
    | '/api/internal/tick'
    | '/api/media/$'
    | '/_app/history/'
    | '/_app/people/'
    | '/_app/wardrobe/'
    | '/api/garments/$garmentId/photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiGarmentsUploadRoute: typeof ApiGarmentsUploadRoute
  ApiInternalTickRoute: typeof ApiInternalTickRoute
  ApiMediaSplatRoute: typeof ApiMediaSplatRoute
  ApiGarmentsGarmentIdPhotoRoute: typeof ApiGarmentsGarmentIdPhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people': {
      id: '/_app/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/history/': {
      id: '/_app/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AppHistoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/$date': {
      id: '/_app/history/$date'
      path: '/history/$date'
      fullPath: '/history/$date'
      preLoaderRoute: typeof AppHistoryDateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/catch-up': {
      id: '/_app/history/catch-up'
      path: '/history/catch-up'
      fullPath: '/history/catch-up'
      preLoaderRoute: typeof AppHistoryCatchUpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/_app/people/$memberId': {
      id: '/_app/people/$memberId'
      path: '/$memberId'
      fullPath: '/people/$memberId'
      preLoaderRoute: typeof AppPeopleMemberIdRouteImport
      parentRoute: typeof AppPeopleRoute
    }
    '/_app/wardrobe/': {
      id: '/_app/wardrobe/'
      path: '/wardrobe'
      fullPath: '/wardrobe/'
      preLoaderRoute: typeof AppWardrobeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wardrobe/$garmentId': {
      id: '/_app/wardrobe/$garmentId'
      path: '/wardrobe/$garmentId'
      fullPath: '/wardrobe/$garmentId'
      preLoaderRoute: typeof AppWardrobeGarmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/garments/upload': {
      id: '/api/garments/upload'
      path: '/api/garments/upload'
      fullPath: '/api/garments/upload'
      preLoaderRoute: typeof ApiGarmentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/tick': {
      id: '/api/internal/tick'
      path: '/api/internal/tick'
      fullPath: '/api/internal/tick'
      preLoaderRoute: typeof ApiInternalTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$': {
      id: '/api/media/$'
      path: '/api/media/$'
      fullPath: '/api/media/$'
      preLoaderRoute: typeof ApiMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/garments/$garmentId/photo': {
      id: '/api/garments/$garmentId/photo'
      path: '/api/garments/$garmentId/photo'
      fullPath: '/api/garments/$garmentId/photo'
      preLoaderRoute: typeof ApiGarmentsGarmentIdPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppPeopleRouteChildren {
  AppPeopleMemberIdRoute: typeof AppPeopleMemberIdRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppPeopleRouteChildren: AppPeopleRouteChildren = {
  AppPeopleMemberIdRoute: AppPeopleMemberIdRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppPeopleRouteWithChildren = AppPeopleRoute._addFileChildren(
  AppPeopleRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppPeopleRoute: typeof AppPeopleRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHistoryDateRoute: typeof AppHistoryDateRoute
  AppHistoryCatchUpRoute: typeof AppHistoryCatchUpRoute
  AppWardrobeGarmentIdRoute: typeof AppWardrobeGarmentIdRoute
  AppHistoryIndexRoute: typeof AppHistoryIndexRoute
  AppWardrobeIndexRoute: typeof AppWardrobeIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppPeopleRoute: AppPeopleRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppHistoryDateRoute: AppHistoryDateRoute,
  AppHistoryCatchUpRoute: AppHistoryCatchUpRoute,
  AppWardrobeGarmentIdRoute: AppWardrobeGarmentIdRoute,
  AppHistoryIndexRoute: AppHistoryIndexRoute,
  AppWardrobeIndexRoute: AppWardrobeIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiGarmentsUploadRoute: ApiGarmentsUploadRoute,
  ApiInternalTickRoute: ApiInternalTickRoute,
  ApiMediaSplatRoute: ApiMediaSplatRoute,
  ApiGarmentsGarmentIdPhotoRoute: ApiGarmentsGarmentIdPhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
