apps:
    web:
        BETTER_AUTH_SECRET: ENC[AES256_GCM,data:SeWh2XeELCuUhRvSXYvNzZp0hsLwOQ737BQRHz7drea2fDsEXRsS2hV4S52hQciRiVM89lcajZlV1M6mkwvEfQ==,iv:ppb3rsdf5l74UlLthaijGMCvtJ/TnsilWgvglGF4Zfg=,tag:PC3YqNLrUH+ggqSHe5KMXA==,type:str]
        GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:G0GrXI5hdu6G92NXg3fS/II0sf/DRgK8MvVsk1eeulEQskB2XaXGTA==,iv:HnZ2mGcNidGuq2xZLWWCvnWgo8F5DuWdssY323dQ6gc=,tag:IX34IqX03xJE80eCq+idsw==,type:str]
        FOUNDRY_OPENAI_API_KEY: ENC[AES256_GCM,data:RONzmJyroYUJmhhw5p9JPW2p9KB7E6xoIhr2f7aZceijM8TliMUPC3ApULkGQ88EeHi29mOV1ooKU+ZF99G5g3xLpM6Ep7CuPP8jMAn27c1Olqew,iv:Arqo3Iv+Rvo1Avpu8WND9NUmnhBvrnandhV9yEwigQ0=,tag:VPYV5Oq1Kx1gzIsim8IUYQ==,type:str]
        AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:UW2RGlq7zxv3oZMMCBHxsZpdUpo=,iv:QHYipqVdPDrXxJqQJ28mFP/wUFRb68kkOC+oQeOZciE=,tag:LUVYxCEQGO1++d/M8QCgMA==,type:str]
        AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qLpHm4kPn6YwWomULwtq27a9Fh+Fy6xS+ycRxbZr+X6YBPSnIiLMOw==,iv:l0It4RbMMVnoAxlxosDzTsayNAAxd6q0UAg5lt2LC8A=,tag:biTKQ1ixUSUg9Im6F39X0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOHpod2s0aEFGUVpjb2FS
            N25BNE9nUENTdW9rSmNSa0x3TGJPTTBqaEhJCkhibE5pSU90bERwdUlicHc5clpE
            WC93cXZjQXZSM1dmNXFtajgxRXJQemsKLS0tIHk4aVFiVWIzMWRNR3ZzU2RWaUxK
            NlFwbTljVUtTT3R6cEd2VmM4cjcyWUEKKwSoIgr6W/7cK4spWbRz/LJLjU4d6cLn
            Xz/uCkoeKLhR+/ovBVXoDykEMqsq6Z32EG6cLxxByjlYp+KfDPSutA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gxzu2f027zu227f4wyf4jh5sw0w495482qfzv5flmfyjvgzxm3ys8p9muz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaUhhWVlYcWsrK3UxbEM3
            bTlnYnYzem5ZK1NqSGZIQU9xKzJDVDFaaVJNCk1HTys4Q1h3dVI1WHNEVXltWlRD
            cGRlSk9kVWdQVjBvTW92MGxoT1MxQmcKLS0tIDZMdVZSMkFuQ3FSbU5PckFYM2Za
            cjBkclZVbFJPMjNCcGpnZVZhemxpSm8K+kBc0aKQEXmy6XWWNMUnTeququThrpLb
            SglACeiDa0i08XQEJ+L3VJM8rDM82B5sNmU4ZACPxNTikU0At7UQLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cgudsv52h62snquglvayft2n4ck522x4at5aja57un06w9w0gszqzfqtce
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WVdxT21FSHk0ZzQ3K21l
            TFFRZmNIbVJjYStIODBWUjJSRm1BdE9hbDBvCi9xZ3ppRFpucWV1YnV3TDJZYmZG
            aWpFeUVZc05nWXFSYmw0elRBK3VmdHcKLS0tICtDaENyTWt4WGU4QWFxU0pjZ2cr
            ODRzVTE3ellScVI1bWZaV0wyajhPTUUK7CpiKU8iaiJRPOH/LY+9/zBkISvWSt87
            5YrU3NbmcUUF7DysUsaElKBraP98NGeNrV0uHNCV4ZC9MfokB51lhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j4lkxpdweugkfz900u023kx8p6k7yuhdp8jmxthj0qse3w6ahfesyqnj96
    lastmodified: "2026-10-01T20:50:56Z"
    mac: ENC[AES256_GCM,data:W/EgJqD6TgmURTind1hx8kdl0z0R3DuaL5pJR/mKy9+BOUm/bXpOtoiGSZRF3A3jcYJEUuF3IL5ok1q8SEZpAG3eF262SUPrgU5SRiu0cO5V7j+NSGjHgICrfEx8ZIKX0/sLuk1ntGhQURcvUk1bI8eXSanyGXy+yKJLQcYpqOE=,iv:0XF2uKZFVhTgY9fCdTwUBZZIMfS3WduS3BGABKsoLPE=,tag:ZNVJWrx2dFP/MKsVHNiGzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
